### ISSUE TITLE
'Rate the app' button doesn't link/open a google play site with the app

### ISSUE THREAD

**Issue by aha999** [SamAmco/track-and-graph#1]
Says something like, No app with this name has been found.

**Comment by SamAmco** [comment]
Sorry for the late reply. That is very odd, I'm unable to reproduce this error. The link is simply: 

https://play.google.com/store/apps/details?id=com.samco.trackandgraph 

Perhaps you can try accessing this link via a browser and tell me if it works?

**Comment by SamAmco** [comment]
Closing this issue due to lack of response.
