### ISSUE TITLE
Crashes (and oddities) on renaming groups

### ISSUE THREAD

**Issue by uli-on** [SamAmco/track-and-graph#10]
First: Thanks for writing & releasing this app! The graph comparison is what makes it superior to the other FOSS habit trackers I know!

Each attempt to rename any of the two group types ends in a crash. Same for re-ordering groups, btw. (Renaming & re-ordering tracks works ok.)

App v1.4.3 from F-Droid, Android 6.0.1, Moto G4

**Comment by uli-on** [comment]
Strange things happen: I **can** manage to rename a graph group, but only when its predecessor immediately *above* it is an empty group! But:

After the renaming takes place that group becomes a duplicate of the group immediately *below* it! It changes back to its original type and content after closing it again or after opening another menu entry from the slide-in sidebar.

**Comment by SamAmco** [comment]
Hi thanks for raising this issue. I have played around with creating, deleting and renaming groups a little bit but I have been unable to cause any crashes on my own device. I will keep trying but if you manage to figure out a consistent method to re-create this error from a fresh install then that would be very helpful to diagnosing the problem. Thanks

**Comment by Kozonak** [comment]
Can confirm this also happens for me.

New device that never had the app installed.
Grab latest version from play store.
Create one group with a numerical item.
Create graph group.
Rename any.
App crashes.

Same on P30 Lite 4.9.148 and Samsung Xcover4 3.18.91.

**Comment by Kozonak** [comment]
Can confirm this also happens for me.

New device that never had the app installed.
Grab latest version from play store.
Create one group with a numerical item.
Create graph group.
Rename any.
App crashes.

Same on P30 Lite 4.9.148 and Samsung Xcover4 3.18.91.

I have sent a crash report from the xcover, hope it helps.

**Comment by owlnical** [comment]
I'm experiencing the same problem, although it rarely occurs for me. The name change always goes through, so whatever the problem it is it seems to occurs after the name has been saved.

- TaG v1.4.4
- Android 7.1.2
- Galaxy s7

**Comment by SamAmco** [comment]
Hi everyone. I have found and fixed this bug now I believe so you can expect a patch soon. Thank you for your patience.

**Comment by SamAmco** [comment]
There is now a new version of the app out that should fix this bug. I am pretty sure the bug is fixed so I am going to close the issue. If it occurs again, please let me know and I will re-open it. Thanks for your patience.
