### ISSUE TITLE
[pr] [feature][minor] Longpress on default trackers for specific values

### ISSUE THREAD

**Issue by stheid** [SamAmco/track-and-graph#106]
## Problem

One can set a default value for a tracker, but than clicking on the + will insert the default value into the tracker. However i think its nice if one could also specify a different value when inserting a datapoint

## Suggestion
open the same dialog as for non-default trackers, but only when user did a long-press. This will not change any existing behaviour, but only add an additional behaviour

## Caveat
currently the longpress is handled by the surrounding container and is used for dragging and reordering the cards. I am not sure if this will cause issues in the implementation

**Comment by stheid** [comment]
I would be interested to implement it. So if you deem this request usefull it would be nice if you could give me a pointer to the relevant parts in the code. I have no Android experience and would like to learn a little.

**Comment by SamAmco** [comment]
Totally agree. I have been thinking of adding this my self but have not had the time even though it should be really quite simple. Take a look at FeatureAdapter and DisplayTrackGroupFragment (you will want something like: binding.addButton.setOnLongClickListener). It would be really nice if we could add this behaviour to the tracking widget also although i'm not sure how easy that will be.

**Comment by stheid** [comment]
No the PR is already done :D Let me know if everything is cool :)
