### ISSUE TITLE
Import / Export problem

### ISSUE THREAD

**Issue by McHaupt** [SamAmco/track-and-graph#120]
First of all, thank you for the successful and great app. I think it is great ... because of its flexibilty.

But I have problems with the import/export. 

**Import** 
When importing i get the screen to select a file. After selecting the button select file, selecting a csv file and pressing the import button i find nothing new in the app and no comment about the imported values .. also no error message. 

Are there any special format requirements for the csv files? 

**Export**
When I press the export button in a group with one tracked set of data I get a screen to select a filename with a circle (clock symbol) rotating above. Using the button in the filemenue a name with the group and date is suggested. When I press save I get back to the screen to select a filename. The selected filename is not displayed. After pressing the export button I find in the android file manager a file of the selected name, but of size 0 bytes.

What is going wrong? 

I use android 11 / miui 12.5.3 in german environment. 
The Track&Graph-App is allowed to access the files.

Thanks a lot for an answer in advance

_PS: I could still make small improvement suggestions to the German texts. How to do this?_

**Comment by tristanbrown** [comment]
I'm also having this issue. Exports create an empty csv file.

Android 11.

**Comment by Self-Perfection** [comment]
I have this issue as well.

Looks like this a regression in 2.0.x versions. In Track&Graph 1.x this dialog shows checkbox list with tracked values in current group that allows selection of values for export. But in 2.x this list apparently is never loaded. Rotating circle seems to indicate waiting for the list. Therefore a user can't select values for export and Traсk & Graph exports exactly what it have been told to: csv for no single value as none were selected.

**Comment by SamAmco** [comment]
Thanks for pointing this out guys. I believe you are correct @Self-Perfection this was a regression in 2.x somewhere. I should have fixed this bug in 2.0.4 so please re-open if it happens again.
