### ISSUE TITLE
Cards offset to left after last update (2.0.4)

### ISSUE THREAD

**Issue by Exomancer** [SamAmco/track-and-graph#128]
I like your app alot.  Thanks fir writing it.
After last update to v2.0.4 in portrait mode all the cards/tiles to enter the data and the resulting graphs are all offset to left leaving the right third empty.  In landscape everything is small tiles. In the last version the cards and graphs in portrait mode went completely across the screen.  To me this is more important for the graphs as it makes them smaller.  Clicking on them to see them full screen in portrait mode distorts them too much to be usable so I always viewed them as stacked tiles/cards which are now 1/3 smaller.  The added benefit with the cards/tiles going all the way across in portrait mode was that it was easy yo compare graphs which I do regularly.  The actual data entry and graph editing fields are full screen in both portrait and landscape modes which is great.  If this change is by design, this breaks some of the previous functionality by making us click on the tiles to view distorted graphs or look at much smaller tiled graphs and wasting 1/3 of the screen real estate which is a pain especially when comparing graphs ehich was easy when they stacked across the screen.  If this is necessary, can we have an option to change the tile charateristics?

I'm using:
Samsung Galaxy 4S (T830) Tablet
Android 10

Thanks.

**Comment by SamAmco** [comment]
Unfortunately this is a natural consequence of the new structure where trackers and graphs may be stored alongside each other in the same group. I guess I will need to implement a setting for this somehow to support the old behaviour. Sorry about that.

**Comment by Exomancer** [comment]
Thank you very much for your reply.  A setting for that would be nice.

Oct 9, 2021 2:19:53 PM Samuel Harvey-Collins ***@***.***>:

**Comment by SamAmco** [comment]
I can't remember when but i fixed this I think.
