### ISSUE TITLE
[Feature Request] Add sum options to graphs

### ISSUE THREAD

**Issue by kypi** [SamAmco/track-and-graph#131]
I have several trackers where I just mark 1 when something happens. I'd like to be able to see daily/monthly counts as a sum so that I could see trending monthly  or daily sums as bar/line charts. Right now my graphs just look like straight lines with no indication when an event happened.

**Comment by SamAmco** [comment]
For each line you can select plot monthly total or plot weekly total rather than plot when tracked.
