### ISSUE TITLE
week starts on sunday?

### ISSUE THREAD

**Issue by szamanr** [SamAmco/track-and-graph#136]
i have a tracker with a graph that plots weekly totals. i have only one data point for the current week, with a value 0.5 on monday. i also have two data points on the previous sunday with 0.5 and 0.5 points each. that previous week also has values on other days, 1.5 points in total (excluding the sunday).

![values](https://user-images.githubusercontent.com/2622838/141819590-887b48a2-f1b1-4682-a25b-e4e8ec0cd086.jpg)
![graph](https://user-images.githubusercontent.com/2622838/141819596-3935e582-240b-406d-bd39-a19222a3c224.jpg)

## expected result:

my graph should show 2.5 for previous week and 0.5 for current week.

## actual result:

my graph shows 2.5 for previous week and 1.0 for current week.

---

at first i thought it counts some values twice, but it seems like it considers sunday to be the first day of the week for some reason (if i change the value on the last sunday, it affects the current week but not the previous). 

i did some research and it turns out some countries actually consider sunday the first day of the week. but the [ISO defines week start as monday](https://www.wikiwand.com/en/ISO_week_date). so this should at least be the default with the option to change it in settings.

**Comment by SamAmco** [comment]
Hi. Thanks for pointing this out. You're not the first person to notice this but there wasn't actually an issue for it. You are right that it should be configurable. There has been some development that should support this configuration but the UI has not been implemented yet. Can't say when I'll get to it but it's on my radar.

**Comment by SamAmco** [comment]
Update on this. I think what you are actually seeing here is a bug. It should be fixed in the latest release so please let me know if you still see this problem. Thanks

**Comment by szamanr** [comment]
@SamAmco it appears to me that the issue still occurs for existing trackers but is fixed for new trackers.

i believe this is a time zone issue. i'm in UTC+1 (CET) and my data point is on sunday at 23:45 and is being counted as next week. if i change the time to 22:45, it is correctly counted as current week.

if i set up a new tracker, this issue doesn't occur.

the issue is with the tracker, not just in the graph. if i add a new graph for the same tracker, the same thing happens.

i'm on version 2.1.0.

**Comment by SamAmco** [comment]
This issue was fixed in version 2.1.1. It was indeed a time zone issue. I'm looking at your original example and it looks like you're saying that the data in the tracker is correct but the data on the graph is wrong? As I say I believe this bug should be fixed in 2.1.1.

**Comment by SamAmco** [comment]
Also if your clocks went forward/backward recently then this could also be related to why you were seeing the issue before but not anymore? Again this should still be fixed in 2.1.1. Otherwise if you could please post the data in v2.1.1 that is showing an issue (as you did above) that would be very helpful. Thanks

**Comment by szamanr** [comment]
@SamAmco thanks, noted. i updated to v2.1.0 yesterday and don't see v2.1.1 available. has it been submitted to the f-droid store yet?

**Comment by SamAmco** [comment]
F-Droid builds the app its self. It can sometimes take a while to pick up, build and release new versions.
