### ISSUE TITLE
[Bug] Reminders incorrect across daylight savings / timezones

### ISSUE THREAD

**Issue by e-t-l** [SamAmco/track-and-graph#139]
### The problem

When the time changes, e.g. due to daylight savings or the phone's clock changing timezones, Track-And-Graph's reminders get off schedule. Restarting the phone get sit back on the right schedule. 

### Hypothesis 

I haven't dug through the source code, but it looks like reminders are on a 24-hr cycle, instead of being triggered by the clock. So, if a reminder is set for noon, then autumn daylight savings occurs and clocks gain an hour at 2am, then the next reminder will occur at 11am instead of noon (aka 24 hours after the previous one). Likewise, if the user travels from the US west coast to the US east coast (+3hr time difference), then the next reminder will occur at 3pm instead of noon. 

### Workaround/Solution

As mentioned above, restarting the phone appears to correctly sync reminders according to the current system time. This is only a temporary fix, though, as daylight savings and/or travel are inevitable for the majority of users. A better solution would be for reminders to be triggered by system time (or by querying Unix time) instead of relying on a 24-time interval from the previous reminder.

**Comment by SamAmco** [comment]
Well spotted, thank you.

**Comment by SamAmco** [comment]
I took a look at this and I think i've figured it out, there should be a fix in the next release. All reminder notifications use the android AlarmManager which schedules alarms in UTC. The reminder should always go off when your device clock says the same time as the reminder. This means if your clocks change I need to cancel all scheduled notifications and re-schedule them against the new clock. There were a couple of issues with reminders but i think they should be squashed now.
