### ISSUE TITLE
[Bug] Keyboard not hidden on home button press in InputDataPointDialog

### ISSUE THREAD

**Issue by iotadaimon** [SamAmco/track-and-graph#143]
See attached video. This happens only when done for the first time, all consecutive attempts with the dialog open successfully hide the keyboard. Dismissing the dialog and bringing it back before pressing the home button makes the keyboard reappear on the home screen. I'm not very familiar with the code, but something like `requireActivity().window?.hideKeyboard(binding.viewPager.windowToken)` in `onPause()` seems to fix the problem for me.

https://user-images.githubusercontent.com/14964363/145679072-6d8ec90e-809e-48cd-b349-801757e19dd4.mp4

**Comment by SamAmco** [comment]
Interesting. I do not see this issue on my device but i can try your suggestion at some point. Thanks

**Comment by stheid** [comment]
Can confirm Issue AND fix. will be joined in another PR in the next days

**Comment by stheid** [comment]
actually i think the two issues are closely linked. i think my "fix" of this issue causes #165. not sure if #165 is actually relevant

**Comment by stheid** [comment]
I can confirm the issue and i think its related to https://developer.android.com/reference/kotlin/android/view/inputmethod/InputMethodManager#show_forced

**Comment by SamAmco** [comment]
Ok following @stheid PR here: https://github.com/SamAmco/track-and-graph/pull/171  This should be addressed. That said i never was able to replicate this issue so if it happens in a version >= 2.3.x then please raise this again and perhaps let me know what version of android you're running as that could be the culprit.
