### ISSUE TITLE
Feature Request: Start tracking & stop tracking

### ISSUE THREAD

**Issue by zaphbbrox** [SamAmco/track-and-graph#15]
Hi,

first of all: 
Thank you very much for your app!!!
I was looking for something like this for a long time.

I think it would be nice to have the ability to start tracking something time-based and then stop it at some point.
For example:

- start tracker **watching TV** _no I won't binge-watching_  

_few hours later:_
- stop tracker

Currently I track time-based stuff with the numeric option, counting it in minutes.

_Edit: Also thx for putting it on fdroid !_

**Comment by SamAmco** [comment]
Hi. This is a great idea. I did want to put in a time based track type so I will probably aim for that first, after that it would be nice I agree to be able to start and stop a timer your self in the app. I have very little time to dedicate to this project at the moment though I am afraid so i'm not sure how long it will take to get this done.

**Comment by SamAmco** [comment]
Hi @zaphbbrox. Thank you for your patience so far. You will be pleased to know that the new version (coming soon) will have the time duration option as an input type. Timers are still not implemented unfortunately and there are a few other priorities I have above this at the moment, but they are definitely on my wish list too.

**Comment by sgofferj** [comment]
Start/stop buttons could even be widgets...

**Comment by stheid** [comment]
implemented in #161
