### ISSUE TITLE
Feature request: ability to set "end of day" time

### ISSUE THREAD

**Issue by walbergs** [SamAmco/track-and-graph#152]
Binning days between midnight is arbitrary for people who's "day" doesn't end at that particular time. It would be much more useful to have a setting where we can specify an "end of day" time and have the graph reflect accordingly.

Example: pub/bar closes at 2am. Recording drinks until that time shows two days of alcohol consumption when, for all intents and purposes, should be binned as a single day on the graph.

**Comment by SamAmco** [comment]
Closing as duplicate of #130
