### ISSUE TITLE
feature request: translations

### ISSUE THREAD

**Issue by Sneffel** [SamAmco/track-and-graph#157]
I'd volunteer to translate the app into Italian. Just let me know when and where I can do it.

**Comment by SamAmco** [comment]
Hi. Very late reply i'm sorry, i missed this issue the first time. Although i appreciate the offer, it's challenging for me to support lots of languages. Every time i update or change the app i have to update/change the translations. Typically at that point I end up turning to google translate. It's also very difficult for me to QA your translations. Again i end up putting everything in google translate and checking that it's roughly correct. For a technical app like this precise language can be really helpful, so translations are always a concern. I would rather support a minimal set of common languages for now. Sorry.
