### ISSUE TITLE
Issue -taping outside of keyboard while writing notes immideatly closes input field WITHOUT saving!😱,

### ISSUE THREAD

**Issue by Rubylion** [SamAmco/track-and-graph#159]
Hi. First of course thank you for providing this useful app.
I use your app quite a while and often need adding longer notes to the tracking values.

So the problem is, while writing and I accidentially tap a litte off of the keyboard, the notes field closes immediateley and nothing I wrote has been saved. All gone. Half an hour writig...(by the way, I absolutly support the text input box request). This really happens to me quite often. I absoluteley would appreciate it if you could fix this. Maybe blend in a save/discard/abort question at this time. Or just backup the text in very short Intervalls, or.... don't know how. Not a programer.
Thank you

**Comment by stheid** [comment]
i think you refer to #151

**Comment by SamAmco** [comment]
No @stheid this is a different issue. Closing the dialog when you touch outside of it is standard expected behaviour. Having a confirmation if you've entered a note might be a good idea but I'll have to see when I can get to it.

**Comment by Rubylion** [comment]
I understand, that tapping outside can be a closing option. I think that because the entrance field is that small = 1 line, it happens just very often. Maybe redesign as opposed by another user as textfield could also solve this problem. Thanx

**Comment by stheid** [comment]
@SamAmco agree, i saw this as a compound-issue, but thats an irrelevant discussion ;)

**Comment by Rubylion** [comment]
I read through the thread and was just remembering it would be just totally fine to close the input field by tapping outside of it. The real issue is actually, that nothing is been saved when closing!. By the way still an expandable inputfield The real issue is actually, that nothing is been saved when closing!would be great, as enhancement.

**Comment by Itradetime** [comment]
This issue still exists. I have been using the notes feature to update status in different timeline of my project and I clicked outside after writing 100s of words! And that was not the first time either. So is it possible to add a dialog box asking if we want to save the text before exiting? Maybe only when the user has typed something. Or a global setting to turn it on or off? 

I really love to take notes in this app, but this one bug is preventing me from having a good experience.

**Comment by SamAmco** [comment]
I never realised people would write such long notes, sorry guys. I don't really want to implement saving your note, it seems a bit overkill, but I can certainly put some measures in place to avoid accidentally closing the dialog. I'll disable close on touch outside the dialog and add a confirm dialog if you click cancel when you've written anything in the notes section. This will be in the next release.
