### ISSUE TITLE
Reminders: editing days resets reminder text

### ISSUE THREAD

**Issue by danipozo** [SamAmco/track-and-graph#16]
When editing a reminder, any change in the weekdays resets the reminder text to the default "Time to track!".

**Comment by SamAmco** [comment]
Hi @danipozo  .. this is an issue I am aware of. The solution for now is to always make sure you click the tick on the keyboard when you're done updating the name. This is un-intuitive though I know and I will aim for a fix at some point soon.

**Comment by SamAmco** [comment]
Took me over a year to get around to this but i think this should be fixed in the next release.
