### ISSUE TITLE
Feature request: option to assume missing values as zero

### ISSUE THREAD

**Issue by eternalbit** [SamAmco/track-and-graph#17]
It seems like track and graph per default connects each two consecutive data points with a straight line (when there's no moving average set).

If I have a data point for day 1 with value 5 and a data point for day 3 with value 7 these will be connected and the graph will look as if on day 2 there had been a value of 6.

It'd be neat to have the option to set a default value (per time period, for example 1 day) of zero (or maybe something else, like the average of all data point values) when displaying the graph. This would lead to each day without a set value being treated as if it were assigned a default value (zero, or something else).

This would lead to more meaningful graphs when the phenomenon being tracked is something like: number of hours of some activity on a given day.

This way of tracking an activity could probably be handled even more easily with a separate new tracking type: 1 numerical value per time period (day,week,...) ... but it could also be included in the existing tracking type, which would make it more versatile.

**Comment by SamAmco** [comment]
Hi, I believe the plot totals feature covers this use case. Please take a look at "How plot totals and moving averages are calculated" in the FAQ section of the app and let me know. Thanks.

**Comment by eternalbit** [comment]
That's awesome. Sorry for overlooking that. Thanks.
