### ISSUE TITLE
2.2.1 Some graphs get stuck in infinite loading

### ISSUE THREAD

**Issue by Kozonak** [SamAmco/track-and-graph#170]
Just updated my app a few hours ago (to 2.2.1) and some of the graphs I have get stuck in loading/refreshing (with the circle loading icon). Fix is to either tap edit on the graph and go back or kill and relaunch app. 

On app homescreen I have a "time since" graph that uses 9k+ tracked items that gets stuck on each app launch and most of the time if I add a new item (video att).

I've noticed some other graphs, in subfolders, taking a lot longer to load or failing to load in the same way.

I have a second "time since" graph that uses 3k+ items and it doesnt seem break, so maybe related to the number of tracked items the graphs are using? But I did notice graphs with very few items also tend to load longer and occasionally get stuck.

MAR-LX1A/Android 9 

https://user-images.githubusercontent.com/3283978/180751498-be8a2d85-815e-4a75-b173-b72e7b9b480f.mp4

**Comment by SamAmco** [comment]
Hi thanks for reporting this, I am aware of the issue and I will try and get to the bottom of it soon. There was a major refactor in that version so i may have introduced a bug or two.

**Comment by SamAmco** [comment]
Ok actually think i've found and fixed this issue already. Should be fixed in the next release. Thanks again.
