### ISSUE TITLE
How to use this app for tracking calories consuption by day/weeks/months?

### ISSUE THREAD

**Issue by stephane-archer** [SamAmco/track-and-graph#174]
I can make a numerical tracker and add to it every time I eat the calories value. But how can I spot the total by day/week/month?

**Comment by SamAmco** [comment]
You want to use the "plot totals" feature. When you create a graph there is a drop down on each line that says "Plot When Tracked" change that to the value you want. You can also change the line style (the zigzag in a circle on the left) to show a number for each data point if that helps.
