### ISSUE TITLE
Plot difference of values by day

### ISSUE THREAD

**Issue by Lucas-Sichardt** [SamAmco/track-and-graph#175]
Hi and thanks for your great tool!

Would be nice to be able to plot a graph that shows the difference between daily values.
I usually track the overall km of my bike every day and it - of course - gives a growing number and an ascending graph.
It would be nice to get a graph with the increase per day (or week or month etc.).

Is this possible?

Thanks and best regards,

Lucas

**Comment by SamAmco** [comment]
Hi not currently possible in the app but i'm hoping to solve this alongside many similar issues with the implementation of #69 that i am currently working on. There are other issues of a similar form so i will close this one. Thanks for the feedback though.
