### ISSUE TITLE
Feature Request: Fixed Scaling for Vertical Y Axis Histogram

### ISSUE THREAD

**Issue by chendy** [SamAmco/track-and-graph#176]
The vertical axis scaling of the histogram is confusing.
The value shown isn't the same as the value of the tracker.
For example, if I put 3 units of reading. It shows up as 0.6 on the vertical Y axis.

1. An option to have direct number representation would be good.
2. An option to specific fixed scaling, like what is available for the line graph.

Thanks well done to you guys! : )

**Comment by SamAmco** [comment]
Hi, the Y-Axis of a histogram should really be thought of more like a percentage. The summation of the area of the bars should add up to 100% (or 1.0 in the case of track & graph) .. Each bar represents the sum of many data points and its height represents that sum in relation to the other bars. I suppose i could allow you to see the raw sum value for each bar, but I wouldn't think it would make much sense in most context's.

**Comment by SamAmco** [comment]
I changed this to a percentage and owing to the lack of response i'm going to close this issue for now.
