### ISSUE TITLE
Graph value for multi choice equivalent too order in list 

### ISSUE THREAD

**Issue by HeartOfChains** [SamAmco/track-and-graph#177]
I was planning on using this app to track my motivation over time based off the amount of tasks or exercise I did throughout the month.
To provide better motivation for me to do stuff I had a preconfigured set of tasks which when I would complete them I'd add them too the task.
Then I realised that the graph didn't count how many tasks I was doing but instead their order

**Comment by SamAmco** [comment]
Yeah each data point has a numerical value which, in the case of multiple choice, is defined by the 0 based index of that choice. I would suggest you set up a second tracker (numerical with a default value of 1) and track that every time you do a task as well, then graph your daily total of that tracker for example. I'm currently working on a feature (#69) which would enable you to write a function based on your original tracker that just has a value of 1 for each task, so eventually you should be able to have one tracker.

**Comment by SamAmco** [comment]
I think in the future I will also allow multiple choice "labels" to just be optional extra values un-related to the numerical value of the data point, but for now each multiple choice answer has one and only one numerical value and that value is the index of the choice. The original idea was that this allows choices like "Small", "Medium", "Large" to make sense numerically but i realise this is probably a little restrictive.
