### ISSUE TITLE
"ADD" button should read "SAVE" when editing datum

### ISSUE THREAD

**Issue by YoshiRulz** [SamAmco/track-and-graph#186]
I think it's this? I'm not yet familiar enough with Android to know how to make it conditional, or I'd just PR.
https://github.com/SamAmco/track-and-graph/blob/e85d8b24a31ba434bcc9457e59364f350ff68665/app/src/main/res/layout/data_point_input_dialog.xml#L79

**Comment by stheid** [comment]
It has to be updated conditionally in the code, as this dialog template is used in multiple locations.

**Comment by SamAmco** [comment]
I'm rewriting this UI right now so I'll consider this as I go.

**Comment by SamAmco** [comment]
Changed it to say update
