### ISSUE TITLE
All-time sum/average

### ISSUE THREAD

**Issue by Vuenc** [SamAmco/track-and-graph#188]
To the moving average options for a graph, I would like to propose to add the following options:
- all-time average
- all-time sum

The use-case I have in mind is to plot quantities where I track incremental changes every day, but where in the end I am interested in the sum over these incremental changes (e.g. track +1 every time a new member joins a group, or +1 every time I do a certain chore) and would like to see in the graph how that sum changes over time. Currently I use the annual moving average for that purpose, but as soon as I'll have > 1 year of data that will not work anymore.

Depending on if you think it makes sense, one could also add "moving sum" (or "moving total") options as alternatives to the existing "moving average" options, e.g. weekly moving total, monthly moving total etc. However I think the most important use case is the all-time total.

**Comment by SamAmco** [comment]
I'm currently in the process (very slowly) of implementing #69 which will hopefully allow you to do things like this with scripting. I don't want to weigh the UI down with any more options as it's confusing/offputting for new users. Also there are lots of other potential transformations people want to do on data, so ultimately i think it's best to do stuff like this with a script. Working on it though :)
