### ISSUE TITLE
Plot sum of data since start

### ISSUE THREAD

**Issue by imbibinebe** [SamAmco/track-and-graph#192]
Hello.
This would be a feature that would be really useful to me.
As an example, if you have this:
t0 -> 1
t1 -> 0,5
t2 -> 2
it would be great to be able to plot
t0 -> 1
t1 -> 1,5
t2 -> 3,5
I subscribed to beta version of the app and would be glad to help developing this feature if needed.

**Comment by SamAmco** [comment]
Sorry i don't understand what you mean here can you explain your issue in more detail

**Comment by imbibinebe** [comment]
Hi,
Sorry as well for my bad english... 
I mean it would be interesting to be able to plot the sum of a data since it started to be tracked.
As an example, I'd like to track energy coming from photovoltaic units everyday. If I tracked :

Day 1 : 2 kwh
Day 2 : 1.5 kwh
Day 3 : 12 kwh

I would like to be able to plot:

Day 1 : 2 kwh
Day 2 : 2+1.5 = 3.5 kwh
Day 3 : 2+1.5+12 = 15.5 kwh

Do you see what I mean ?
