### ISSUE TITLE
Focus value field

### ISSUE THREAD

**Issue by HappyDustbunny** [SamAmco/track-and-graph#196]
Please let the value field have focus when adding data. The extra tap slows me down.

Also the add-value box is too small for histogram entries. And if you have very long names in histogram choices one of the buttons is off screen.

Thanks in advance :-)

**Comment by SamAmco** [comment]
Hi sorry can you show me what you mean about the histograms? I'm not sure what you mean by the "add-value" box for histograms?

**Comment by SamAmco** [comment]
Version 3.0.1 focuses on the value field if you have no suggested values which is basically the same as the previous implementation v2.3.5 where multi-choice doesn't focus but numerical does.

**Comment by SamAmco** [comment]
Please create a different ticket for the histogram thing with more details (preferably screen shots) .. it's not clear to me what you mean.
