### ISSUE TITLE
Feature request: Convert time tracking to numerical

### ISSUE THREAD

**Issue by xerus2000** [SamAmco/track-and-graph#20]
I have a stat where I used to only track time, but now I want to track it numerically because I don't want to click it multiple times every time. I don't understand why I can't simply convert it to a numerical tracker where all existing values simply stay as 1?

**Comment by SamAmco** [comment]
You're right about that. There isn't really a good enough reason for this. I will look to change it soon. Thanks for the feedback.

**Comment by SamAmco** [comment]
I have fixed this issue on master now, the fix will be in the next release

**Comment by xerus2000** [comment]
Thank you :)

**Comment by SamAmco** [comment]
@all-contributors please add @xerus2000 for ideas and bug
