### ISSUE TITLE
Issue: When editing the date in a tracker entry, the date is wrong

### ISSUE THREAD

**Issue by ruvilonix** [SamAmco/track-and-graph#200]
If I go to an entry in a tracker and I click on the Date chooser, then select a date, when I press OK, the date has been set to one day earlier than I selected. For example, if I select 14/1/23, the date will be set to 13/1/23.

https://user-images.githubusercontent.com/114708614/223000071-4ccca2c9-ee82-4774-8feb-680f8e88e791.mp4

**Comment by ScalableCodex** [comment]
Yup same issue.

**Comment by SamAmco** [comment]
Hi, thanks for the report. I am aware of the issue. Unfortunately I'm away until next Tuesday now but this is high priority for sure.

**Comment by SamAmco** [comment]
Hey. v3.0.2 has been released and should fix this bug. Thanks for your help and patience.
