### ISSUE TITLE
Question about creating a new tracker

### ISSUE THREAD

**Issue by froyglez** [SamAmco/track-and-graph#203]
In the spanish version, when I'm about to create a new tracker, there is an option asking for the kind of data, but it only allows me to select, not to specify the kind of data. Is this a bug? Thanks in advance!
![WhatsApp Image 2023-03-09 at 5 17 05 PM](https://user-images.githubusercontent.com/60108777/224182661-02d2f649-fc6d-4ea7-9d8e-b6edd5d4fd5a.jpeg)

**Comment by SamAmco** [comment]
Hi this is not a bug this is V3 .. there is no such thing as multiple choice anymore. Any data point can have any value or label now. The value/label suggestions are made by looking at previously tracked values. You can modify the suggestion behaviour under advanced. Check the FAQ for more.
