### ISSUE TITLE
Time picker always resets to 00:00

### ISSUE THREAD

**Issue by steel-steven-87** [SamAmco/track-and-graph#205]
Version 3.0.0 or 3.0.1 (can't remember exactly) brought an inconvenience.

When you click on the time in this screen:
![img1](https://user-images.githubusercontent.com/89798696/225755335-66f78787-e059-4331-9163-774a1846c9fb.png)

The time gets reset to 00:00:
![img2](https://user-images.githubusercontent.com/89798696/225755356-ee5c61a8-1e91-4576-bb3e-05de7ff90b39.png)

I used to be able to add an activity and then just shift the time by a couple of minutes quite easily. Now I need to enter the whole time which is a significant inconvenience compared to the previous behavior. The previous behavior was so nice in comparison.

Would it be possible to bring it back?

**Comment by SamAmco** [comment]
This should be fixed in v3.0.2
