### ISSUE TITLE
[French] Minor error translation 

### ISSUE THREAD

**Issue by supersarma** [SamAmco/track-and-graph#206]
Hi,

###  New Tracker

1. Click on "+" (in order to track something new)
2. Tracker
3. The English version of the app shows the box with this text : "This is a time or duration".
This is perfectly clear. (No question mark)

However, the French version shows "De quel type de données s'agit-il ?" which means "What kind of data it is ?"
As you can see, the French version ask a question. When you are new to the app and click on this box, obliviously you expect a multiple input choice... 

In my opinion, the better translation would be "**Il s'agit d'un temps ou d'une durée**.".

### Backup and Restore section

Also, in the Backup and Restore section, the Frech translation can be better. (Open the left side panel -> Backup and Restore)

Current version :
English : French 

"Backup data" : "Données de la sauvegarde".
"Restore data" : "Restauration des données".

The standard translation of this kind of operation is : 
"Backup data" -> "Sauvegarder les données"
"Restore Data" -> "Restaurer les données".

Thank you.

**Comment by zyurs** [comment]
Hello,

I'm taking advantage of this issue to point at another French translation error.
The shortened word for Monday has not been translated: [Source code](https://github.com/SamAmco/track-and-graph/blob/80ab2158ba1a0abbd1fb54af69a2ecab5acbd74d/base/src/main/res/values-fr/strings.xml#L189)
**Mon** should be translated as **Lun** (for Lundi)

Thank you

**Comment by SamAmco** [comment]
Thanks I'll try make sure i update these in the next release
