### ISSUE TITLE
Feature request: Default value when tracking

### ISSUE THREAD

**Issue by xerus2000** [SamAmco/track-and-graph#21]
For some things I track, I want to have multiple options, but there's in one which I almost always use. It would be nice if I could configure it to use that value by default when I click the little plus next to it - that way I have the conveniences of pure time-tracking with the option to select another value by editing or when using the track all button.

**Comment by SamAmco** [comment]
This is an interesting idea but I'm not sure I want to implement this at this time. I'm not sure if I could allow this without a somewhat confusing UX. If I think of a good way I will consider it.

**Comment by SamAmco** [comment]
I have now implemented the changes as discussed above and they will be in the next release.
