### ISSUE TITLE
How to make bar graphs?

### ISSUE THREAD

**Issue by ruvilonix** [SamAmco/track-and-graph#211]
I see a picture of a bar graph on the Github page, but I can't find that setting in the app.

**Comment by SamAmco** [comment]
It is the TimeHistogram graph type. You might also want to read the FAQ page here on how it works: https://github.com/SamAmco/track-and-graph/blob/master/docs/faq/faq_3_4.md 

Other types of bar chart are not yet available but they're on my todo list and have been raised in other issues.

**Comment by ruvilonix** [comment]
Oh ok thanks, I didn't realize there was a FAQ.
