### ISSUE TITLE
[BUG] Make the notes scrollable and fix the glitch while typing notes

### ISSUE THREAD

**Issue by Itradetime** [SamAmco/track-and-graph#216]
Reporting more bugs in note taking feature. 

1. While taking notes, the text box grows but doesn't scroll automatically while a new line is inserted. This means that we have to manually scroll the screen when we press enter key everytime till 8th line. The automatic scrolling works when a newline is inserted if there are more than 8 or so lines. That is the bug goes away after inserting 8 lines. You can reproduce the bug by clicking notes and pressing enter/return key. For the first 8 times, the box grows but doesn't automatically scroll. After 8 lines, the box stops growing and automatic scrolling works. 
![img_pp_135](https://user-images.githubusercontent.com/119799386/232332057-bb8a699a-30e3-41a4-9eee-e463e5044301.jpg)

2. After taking a long note, if the text is bigger than the size of the screen, we can't see the entire text since there is no option to scroll. 
![img_pp_134](https://user-images.githubusercontent.com/119799386/232332070-187e2f1f-9473-45e2-bb29-19fbded267de.jpg)

By fixing these two bugs, note taking in this app can be very enjoyable. Thanks.

**Comment by SamAmco** [comment]
Thanks, I'll try and look into this soon

**Comment by Itradetime** [comment]
Hi @SamAmco, the first issue of automatic scrolling not being implemented is fixed, thank you so much for that. 

Just a kind reminder that the notes are still not scrollable yet. This single feature can massively help me read longer notes. I take notes regularly in this app and right now, to read a long note, I have to click edit and read the notes through the tiny editing window or copy-paste it to somewhere else. Please refer to second part of [this](https://github.com/SamAmco/track-and-graph/issues/216#issue-1670071661) (the first comment of this issue) for more details. Thanks.

**Comment by SamAmco** [comment]
Oh very sorry about that. I completely forgot. Fixed it now, should be fixed in the next version.

**Comment by Itradetime** [comment]
Thanks @SamAmco.
