### ISSUE TITLE
Feature request: Cumulative graphs

### ISSUE THREAD

**Issue by xerus2000** [SamAmco/track-and-graph#22]
There are things I track, such as Meals and different kinds of aches, where I only track when it happens, but I'd like to see correlations in the matter of hours. The problem is that I have to either plot when tracked, which is useless if I never track a 0, or plot daily totals, which are far too coarse.

One option of course would be to plot hourly totals, but what I would actually like is a graph where it automatically descends linearly or exponentially after tracking, but then rises again when I track it another time - e.g. meals: when I eat, the food is processed afterwards, so my saturation gradually descends (simplified, don't mind the complexities of human digestion for now ^^), but when I have anotther snack while digesting the previous, my saturation rises again.

**Comment by SamAmco** [comment]
Hi, thanks for the suggestion. I was thinking hourly totals would be a good idea so I will try to implement that soon. 

In terms of more complex behaviour I would need to look at the UX required to implement this. I would like to avoid features that don't have a very broad use case so something like this needs to be configurable in terms of the rate of descent, the floor of the curve, and the curve type. 

It's a nice idea for a feature but not something I'm looking to implement at this time personally as I have little time to dedicate and other priorities to tackle at this time.

**Comment by SamAmco** [comment]
I have added hourly totals in the latest version, I will release this soon.
