### ISSUE TITLE
Preselect input box and jump to next input on `↵`

### ISSUE THREAD

**Issue by ManDay** [SamAmco/track-and-graph#222]
It would be nice if, when adding new values as a "batch" by pressing the track-FAB, the input field was already selected and pressing Enter on the keyboard confirmed the value.

Current UX:
 - Press "Track" FAB
 - Tap on 1st input field to select it
 - Input 1st value
 - Tap on "Add" button
 - Tap on 2nd input field to select it
 - etc.

Proposed UX:
 - Press "Track" FAB
 - Input 1st value followed by `↵`
 - Input 2nd value followed by `↵`
 - etc.

**Comment by SamAmco** [comment]
Hi. So the existing behaviour is actually quite similar to your proposed UX if you are not using suggested values. The assumption is that when using suggested values most of the time you want to click on a suggested value and not type something new in. If you go to the advanced settings for your tracker(s) you can change suggestion type to none and the suggested values will not show for that tracker and the keyboard will come up immediately. You make a good point that pressing ↵ was not working for adding a value. I've implemented this in v3.5.x for you, but this is currently in open beta on playstore as there are a few other changes in there i want to test a little more. I'll release it soon i'm sure.

**Comment by ManDay** [comment]
Thanks, I'm looking forward to the 3.5 from F-Droid!

> The assumption is that when using suggested values most of the time you want to click on a suggested value and not type something new in.

It works well, after I set the suggestion to "None", like you. But **why not both?*** Couldn't the situation *with* suggestions be the exact same (input box focused, keyboard up) *plus* showing the suggestions?

**Comment by SamAmco** [comment]
It could, and maybe it's just me, but i don't really like the keyboard in the way otherwise i have to reach high up the screen to reach the suggestions.

**Comment by SamAmco** [comment]
Yeah fair enough i can imagine having a setting for this. I'll make a note. I was going to add a settings screen soon.

**Comment by ManDay** [comment]
Cheers, but please don't give it any priority! Since I'm currently not using suggestions I'm happy with the solution you already offered. Just, I could *potentially* see myself having the issue in the future. But bothering you with eventualities just for the sake of it is the last thing I want to do!
