### ISSUE TITLE
glitch with data from the future

### ISSUE THREAD

**Issue by sphuo5g** [SamAmco/track-and-graph#224]
I have a (computer-generated) tracker showing me my target (which is different every day), and another tracker showing my actual data. Now my target values are generated a year in advance. With a graph set to "Sample size: six months" and "Sample ending at: latest", this results in a split graph with six months of my target values starting six months from now on the right, and six months of my actual values on the left; so the graph actually shows a period of 18 months with a gap of no data at all even though the data exists. I’m guessing a similar bug would occur with simply not tracking anything in a tracker for a few days.

I’d expect it to use the same cut-off date for all trackers in a graph.

**Comment by SamAmco** [comment]
It should use the same cut-off date for all data in the graph you are correct. I will try and look into this at some point. Thanks for letting me know.

**Comment by SamAmco** [comment]
Looks like i fixed this a while back and forgot to close the issue. Let me know if you're still having troubles and i can re-open it.
