### ISSUE TITLE
View current day's totals

### ISSUE THREAD

**Issue by zanovis** [SamAmco/track-and-graph#225]
Is it possible to see the current value (summation) for tracking a numerical stat? I.e. tracking calories per day, Id like to see the running total for the current day.

**Comment by SamAmco** [comment]
You can create a line graph for your tracker and select plot daily totals instead of plot when tracked.

**Comment by zanovis** [comment]
> You can create a line graph for your tracker and select plot daily totals instead of plot when tracked. 

I don't think this will plot using the current day's running total, will it?
