### ISSUE TITLE
Data encryption

### ISSUE THREAD

**Issue by Itradetime** [SamAmco/track-and-graph#235]
Is there any plan to add encryption support to the app data? I assume any other rogue app with disk read permission can read the data in android? I am not an android dev so have no clue. How complex would it be to implement a basic encryption with biometric support? Thanks.

**Comment by SamAmco** [comment]
Hi. There is no near term plan for this. It is not possible for any app to read the data of any other app. Only track & graph can read its data (unless you are using a rooted device and you've messed with something, then all bets are off ofc). The only benefit of encryption would be when backing up your data you could i suppose add a password to the backed up file. If you were to save your backup to a public place then it's possible another app could read the data. I really just leave this in the hands of the user right now though. 

Also if you have a modern android device, the whole thing is most likely encrypted by default. 

As a further security measure you can require password/biometric authentication to open an app in most modern android distributions. I have a feature called "App Lock" on my OnePlus for example.
