### ISSUE TITLE
Improved tracker UX

### ISSUE THREAD

**Issue by PropellantDyke** [SamAmco/track-and-graph#245]
Hi,
First of all, thanks a lot for this amazing app!
Here is some feedbacks regarding the UX of the tracker list. I will probably work on it myself for my personal usage, but I can make a merge requests if you want (or for any subpart of it)

Tracker card could be reworked a bit:
- Number of records should be moved in record list page. It's not the kind of information that invite to add more record, and it overload the card.
- Last record date should be displayed as "duration since the last record", to help the user to see if some records are missing for a day. Icon can be removed also.
- Buttons should be less visible to help emphasis the title
- Ongoing recording timer should be displayed instead of last record date, since last record date information doesn't help during recording. This will keep the height of the card constant.
- Tiny detail: margins size around cards and application could be more consistent.

Here is a mockup (right screen), compared with the current version (left screen)

![Screenshot from 2023-11-14 10-57-37](https://github.com/SamAmco/track-and-graph/assets/118541570/710b0ebb-b6ba-410a-9e14-e07972f9f525)

**Comment by SamAmco** [comment]
This is really nice work. Thank you. I'll take a look at your PRs.

**Comment by SamAmco** [comment]
I have merged all of your PRs. Your work looks good and I like the way you split the PRs up into small changes. Really appreciated. I'm going to push this to beta now. If you haven't already please join the beta program on Google play. It should be out within the next 24 hours or so I'd expect. If there are no issues I'll push to release after about a week so please create a GitHub issue if you spot any kind of bugs in the meantime. 

Only thing I noticed is that the screenshots are now outdated. Unfortunately I don't have a good process for generating these. I normally just copy my database and then change the names of the trackers and take screenshots on my phone. Could do with some sort of script to generate a reasonable looking database probably.

**Comment by PropellantDyke** [comment]
Thanks a lot!

It's possible that the project didn't compile with all the PRs merged. This is because I set the visibility of the clock icon in one, and delete the icon in one other. 

I will join beta right now

**Comment by SamAmco** [comment]
@all-contributors please add @PropellantDyke for design

**Comment by SamAmco** [comment]
So i made a couple of updates to this. The only notable UI change is probably that i removed the divider from the tracker card. But I also removed the query for the number of data points from the SQL since this is not necessary any more and just slows down the app. These changes will be in the new beta release. Sorry it's taking me forever to release this I've been meaning to make these changes before releasing and only just now got the chance. I will at least test it a bit locally and then push to full release.

**Comment by PropellantDyke** [comment]
Thanks, I've just tested it, it's much cleaner like this!
