### ISSUE TITLE
Possibility to delete a input

### ISSUE THREAD

**Issue by TMaddox** [SamAmco/track-and-graph#25]
Hey there, first, thanks for this awesome app!

I would like to request the following feature:
After a user inputs something due to a misclick, the value cannot be removed from the track. I would like to request a possibility to delete data points, maybe via a quick edit function.

**Comment by SamAmco** [comment]
Hi. You should already be able to delete data points. If you click in the center of the card you will come to the history view where you can edit and delete previous data.

**Comment by TMaddox** [comment]
You are right, my apologies. Thanks!
