### ISSUE TITLE
Add intermediary form at the creation of a tracker to choose its type

### ISSUE THREAD

**Issue by PropellantDyke** [SamAmco/track-and-graph#251]
Tracker creation could be simplified by creating an intermediary form. This form would appears when the user click on the Add Tracker Button. It would contains the selection of the type of tracker :
- Duration
- Value
- List of labels
- Time point
- Generic

After pressing the button "Next", the user will be redirected to the actual creation form, with appropriate options already filled. Option can even be hidden if they are obvious for a type of tracker.

For example, if the user choose "Duration", the checkbox will be checked and invisible in the next screen.

Advantages:
- Simplification of tracker creation
- Can lead to more options/types since they are no more all displayed together whatever is the type, except if 'Generic' is choose, which is equivalent to check 'Advanced options'
- Can lead to tracker creation from template like 'Weight', 'Running', ...

Open question:
- Is the type kept in database to be used in tracker edition form, or tracker edition would let all the options available?
- What list of types could make sense? The one above is only a suggestion based of my understanding of the actual options

I'm willing to work on it :)

Here is a mockup (big circles should be icons)

![Screenshot from 2023-11-16 22-42-23](https://github.com/SamAmco/track-and-graph/assets/118541570/7a9f120c-a2d8-4f8b-8fb8-b9a9d7415f36)

**Comment by SamAmco** [comment]
Interesting. I need to think about this a bit. I'll try and get back to you soon.

**Comment by SamAmco** [comment]
It looks like maybe you've reconsidered this given your latest issue? I kind of think this might be a bit more trouble than it's worth. I appreciate that creating trackers can be a bit overwhelming for new users. I think your more recent issue is probably a cleaner solution though. If you did it this way you maybe do want to store their options in the database as later a user can click edit on the tracker and they would presumably expect to see what they had selected here. This would require a database migration and could touch quite a lot of code. My other minor issue with this approach is it does add an extra click/screen? I'm not sure about that.

**Comment by PropellantDyke** [comment]
I agree, maybe it can wait finally. I still think that is will be easier to use that way but now that I've played a bit with the code, it seems not so easy to do. I close this issue.
