### ISSUE TITLE
Feature Request: Backup to Nextcloud 

### ISSUE THREAD

**Issue by aproposnix** [SamAmco/track-and-graph#26]
Just found this app today and I love it!

It would be nice if it were possible to backup the data to Nextcloud (or any webdav)

A good use case would be that the user could backup their data to a nextcloud server and then open a Nextcloud app to view that data (esp., dashboard charts or a custom app specifically for this purpose) on the deaktop.

We need a FOSS based personal health monitoring system. Please help build it :) 

Edit: Related but not the same as #12

**Comment by SamAmco** [comment]
Hi. I don't have plans to add specific integration with any particular WebDAV.

You can use the export function which should work with any app that accepts the intent ACTION_CREATE_DOCUMENT. This could be just your local file system on your device or if you have a WebDAV app installed e.g. Google drive you can export directly to that. 

I do want to add a global export and import for all data including graphs and groups. This will likely just export a database file. The schema is public though and there is nothing stopping anyone from building a desktop client to interrogate this data.
