### ISSUE TITLE
Thank you contributers!

### ISSUE THREAD

**Issue by Loppansson** [SamAmco/track-and-graph#263]
This is not an issue (sorry:P). I just wanna say thanks to everyone who is contributing and have contributed to this app! I've been using Track & Graph for a couple of months now, and it's been great; being able to record and easily view the progress i'm making on all the goals i have has been really motivating, and tbh, a lot of fun:)

**Comment by SamAmco** [comment]
Thank you for the kind words. I'm glad you enjoy the app :)
