### ISSUE TITLE
Option to view exact timestamp of last tracked event

### ISSUE THREAD

**Issue by Steve-P42** [SamAmco/track-and-graph#264]
Hi!
First of all - what a fantastic application!! Great work, really, hats off!

I wanted to ask if you could add an option to the settings that rolls back the recent changes of not showing the time and date of the last tracked event as well as the number of tracked events in the tracking cards themselves. Would it be possible to let us choose how to show that? 
IMHO the relative information to now (like yesterday or 12 minutes ago) is really not something I need to know, whereas date and timestamp are crucial tracking parameters that I heavily relied on..

I would be immensely grateful.

If this is not something that can be done, is there a way to roll back to previous builds on fdroid and disable further updates? (Would be a pity to forgo future updates, but oh well, what can you do.)
BR

**Comment by arch-btw** [comment]
Yes, I came here to ask the same thing.

Also, after 1 hour it stops tracking the minutes.

So for example, sometimes I need to know if something was done 2 hours 45 minutes ago. But it will just say 2 hours ago or 3 hours ago, without the minutes.

**Comment by PropellantDyke** [comment]
Hi,

You can still access this information by adding a graph of type "Last Tracked/Time Since". It will gives you the exact last entry timestamp and the elapsed time with precision up to the second for a given tracker.

**Comment by Steve-P42** [comment]
@PropellantDyke

Thank you for your suggestion. However, it is not feasible to add that many graphs, 16 in my case, to have that information shown, which was previously right there at a glance.
Also, I know I can click the Tracker card, and the timestamps are there, as well as the # of tracked items.
 
But these are inefficient workarounds, so I need to find another solution.

**Comment by Steve-P42** [comment]
In case someone else is looking to "solve" this - I am now using Version 3.7.2 indefinitely which can be installed via the application Droid-ify (a sort of fdroid wrapper app) or by downloading the apk from the fdroid website. Droid-ify also lets you ignore future updates, which isn't ideal, but oh well 🤷‍♂️

**Comment by SamAmco** [comment]
Hi @Steve-P42 sorry for the inconvenience. It's probably also worth noting that you can download any version as an APK on the releases page on GitHub: https://github.com/SamAmco/track-and-graph/releases Word of WARNING. Always make a backup before downgrading. Some updates migrate your database and are not backwards compatible. That's not the case here ofc.

Whilst I personally prefer the cleaner design of the new tracker cards I appreciate that some people do want to see different information on that card. Broader customisation of the information on each card is a feature that's been requested for a while now. I will try to update here if and when it's been implemented, but for now I think we're sticking with the new design by default.

**Comment by SamAmco** [comment]
@kaoneko You raise some very good points. I think as I say longer term it would be nice to have broader customisation of what a tracker card shows as different people have different requirements. That should probably be handled in a separate issue though. If I manage to get to it I'll try to improve the tracker time since text behaviour and then close this issue.

**Comment by SamAmco** [comment]
Ok in v4.0.0 (currently in beta) it will show hours and minutes if the data point was within the last 24 hours. There should be an open issue around customisable tracker card display data but i think that's a broader question so i will close this issue for now. I hope this helps a bit in the mean time.

**Comment by kaoneko** [comment]
@SamAmco I've been running the beta today and this small change really feels like a big improvement, thanks a lot!
