### ISSUE TITLE
Sample ending at Today option

### ISSUE THREAD

**Issue by sujayvadlakonda** [SamAmco/track-and-graph#266]
I have a bar chart to track daily totals for a sample size of a week. I would like to see a couple of empty bars when I haven't been doing stuff. A sample ending at today option would be helpful for me. The 'time since' statistic is nice, but I would like to see it reflected on the chart ideally.

Thanks for your work on this application!

**Comment by SamAmco** [comment]
Better late than never i guess. This is a nice idea, I probably should have done this a long time ago. I will try to think about working it in if i get time.

**Comment by SamAmco** [comment]
This should be available in the v4.0.0 (currently in beta)
