### ISSUE TITLE
Default duration is not displayed when editing a tracker

### ISSUE THREAD

**Issue by PropellantDyke** [SamAmco/track-and-graph#269]
How to reproduce the bug:

- Click the button in the menu to create a new tracker
- Check the box "This is a time or duration"
- Define the default duration to "1h 23m 45s"
- Save the tracker
- Edit the tracker
=> The default duration is not displayed ("1h 23m 45s" is not shown)

**Comment by SamAmco** [comment]
Thanks for flagging this i'll try and take a look soon.

**Comment by SamAmco** [comment]
Should be fixed in v4.0.0
