### ISSUE TITLE
Unwanted shift of 1 hour when adding/editing entry - daylight saving time

### ISSUE THREAD

**Issue by eternalbit** [SamAmco/track-and-graph#28]
When adding/editing an entry for 27th of March (as an example), the time gets shifted to - 1 hour.

So when I enter 21:15 the data point gets saved as 20:15.

I suppose it's got something to do with daylight saving time.

If this is intended behaviour then it's at the very least confusing.

**Comment by SamAmco** [comment]
That is odd. I'm not seeing the same issue on my device but you're not the first person to complain about this issue so I will have to try and dig into it at some point. Thanks

**Comment by SamAmco** [comment]
Update: Ok I think I've managed to re-create this issue now. It is a little confusing you are right but not a huge priority right now. Thanks for spotting this.

**Comment by SamAmco** [comment]
Ok I think I've fixed this, it should be working in the next release.
