### ISSUE TITLE
Auto Backup with v402

### ISSUE THREAD

**Issue by ballinger** [SamAmco/track-and-graph#280]
Tried the 402 apk which didn't reach gstore and f-droid. Seems as the app crashes when auto backup triggers. Thanx, phil

**Comment by ballinger** [comment]
App just updated from f-droid without me noticing it. Same behavior, crash when backup is triggered

**Comment by SamAmco** [comment]
Oh dear. I will take another look.

**Comment by ballinger** [comment]
appreciate it

**Comment by SamAmco** [comment]
My appologies. I had another crack at it. I believe it should work in v4.0.3. It's essentially to do with permissions surrounding running work in the background. They changed the requirements in API 34 (Android 14). Oddly enough it looks like there were actually two bugs in v4.0.x .. After fixing one it never occurred to me that there could be yet another bug breaking the app above API 34. Fingers crossed this should put it to rest. Thanks for letting me know.

**Comment by SamAmco** [comment]
@all-contributors bot please add @ballinger for bug

**Comment by ballinger** [comment]
:) all working, Thanx!
