### ISSUE TITLE
Point option for graphs

### ISSUE THREAD

**Issue by compusolve-rsa** [SamAmco/track-and-graph#29]
Thank you brother.

Very insightful piece of code you have written. It has helped me track my ptsd and depression. 

I humbly ask for the option to choose points instead of lines for a given element being tracked.

A typical use case might be watering the garden. Knowing the day it was watered would be very easy with a point marker, since it is hard to see from the line graph when an event occurred.

Namaste.

Lee

**Comment by SamAmco** [comment]
Hi Lee,

Thanks for your suggestion. I absolutely agree that points labels would be a great addition to the app and this is on my TODO list. However please bare in mind that I have very little time for this project at the moment so progress is likely to be slow right now. 

Thanks for your feedback,
Sam

**Comment by SamAmco** [comment]
I have now implemented a solution for this and it will be included in the next release.
