### ISSUE TITLE
Feature Request: Add ability to add comment to data entry

### ISSUE THREAD

**Issue by donpatzone** [SamAmco/track-and-graph#3]
Hi,

first of all, thanks for this app. I **really** like the simplicity as well as the flow to add multiple data points in succession. Import/export of data to CSV is icing on the cake.

One of my use cases is a driver logbook and there I miss the ability to add a comment to a data point where I would typically state the reason or destination.
That comment could be entered alongside the actual data value in a separate line, either above our below the [Cancel][Skip][Add] buttons

Not sure, if our would make sense to add it as a separate input style

**Comment by SamAmco** [comment]
Hi donpatzone, thanks for the feedback. I agree comments would be a useful feature to add and I will consider it for a future release. I don't have a lot of time on my hands at the moment however so I'm not certain when I will be able to add this.

**Comment by SamAmco** [comment]
Hi. I have now implemented this feature and it will be available in the next release. Thanks for your patience.

**Comment by donpatzone** [comment]
Hi,
thanks. I just tried out version 1.6.2, but I couldn't add a description to a datapoint. Is it planned for a later release?

**Comment by SamAmco** [comment]
Yes this is available in 1.7 up. Should be rolled out soon.
