### ISSUE TITLE
Unfortunate default input style when creating a track

### ISSUE THREAD

**Issue by SebiderSushi** [SamAmco/track-and-graph#35]
When creating a track, the order in the inout style dropdown is precisely the reverse of what can be converted after creating.

This is inconvenient if you happen to create your track with the wrong track type, as you cannot simply convert it as soon as you realize and have to recreate your track completely.

A simple solution to this would be reversing the order of the dropdown, or just proposing "Multiple choice" as the default.

Pros of this change:
- If the user remembers to choose the right track type it will be no different from before the reversal/change.
- If the user forgets to choose the right track type, they can conveniently convert it afterwards

Cons of this change:
- Users who mostly create tracks of the current default type "Date and time only" can no longer just leave the dropdown untouched

Alternative solutions could be:
- A setting to customize the default track type preselected in the creation dialog according to the users needs
- A change to the conversion feature that allows any kind of conversion. If nothing is tracked yet, it could automatically do the conversion anyway. If there is already some tracked data, the user could be presented with a dialog asking which value to assume for the existing entries if the conversion is an upgrade. E.g. when converting from "Date and time only" to "Multiple choice", the application could query the multiple choice type list from the user and offer a dropdown to choose a default value for existing track data.
After such a conversion, the user could normally edit the track entries to further correct it.

**Comment by SamAmco** [comment]
Hi @SebiderSushi .. Thanks for the input. There has certainly been some confusion around track types and I think the newer version should clear this up a bit. I have removed "date & time only" all together and have allowed default values for numerical and multiple choice if you want quicker tracking. However you may be right that it is sensible to put multiple choice as the default selected value. I will probably swap them as suggested before the next release. I will let you know.

**Comment by SamAmco** [comment]
Ok I have now swapped this and it will be corrected in the next release. Thanks for drawing my attention to this.

**Comment by SebiderSushi** [comment]
Thank you for taking care of your forgetful & mindless users :D

**Comment by SamAmco** [comment]
Haha no worries, usability is a legitimate concern that can be hard to see when you've been working on something for a long time. Thanks
