### ISSUE TITLE
Wrong digit for month in backup filenames

### ISSUE THREAD

**Issue by uli-on** [SamAmco/track-and-graph#36]
Hi Sam! 
I just observed that backup files use the current month +1 in their names (i.e. today, 29th of May, the app places a 06 inside the filename). That happens no matter whether the backup is invoked from the slide-in menu or via backup button in a track group. That might lead to import outdated data.

Edited to add: 
T&G v1.6.2, Android 6.0.1 (Moto G4 flavor)

**Comment by SamAmco** [comment]
Hi, uli-on thanks for this. That's very odd. I have not been able to reproduce this error and I can't really see how this could happen. I am not modifying the date/time before writing it to file in either case. Taking CSV as an example, I simply call OffsetDateTime's toString function to generate that text: https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#toString--

Have you tried re-importing your exported data in a new track group and comparing it with the original? Is the imported data the same as the original or is it shifted by a month?

**Comment by uli-on** [comment]
I've just tried a re-import and all is well, May is displayed as 05 inside the app.

**Comment by SamAmco** [comment]
Hmm that is odd. It's possible that this is some nuance of OffsetDateTime I'm unaware of. If you want me to look into this further, perhaps you could send a screenshot of the date time in the csv and in the app?

**Comment by uli-on** [comment]
Sam, I'm aware that I'm using a very aged Android version. Cause you said you can't reproduce this and as nobody else has observed that behaviour I think there's no need to invest time and effort into this. I'll manage to keep that oddity in mind and work around it. Thanks again for your app!

**Comment by SamAmco** [comment]
Ok thank you, I'm glad you enjoy the app. Let me know if this causes any further issues and I'll happily re-open this issue.
