### ISSUE TITLE
F-Droid repo not showing the latest releases

### ISSUE THREAD

**Issue by Stochastic13** [SamAmco/track-and-graph#37]
As far as I can see, the latest version on F-Droid is 1.5.1 and 1.5.2 and 1.6.1/2 never showed up in the repo (excluding the pre-releases). Is this intended or is F-Droid builds failing to update to the latest version?

Great app, by the way! :)

**Comment by SamAmco** [comment]
Hi @Stochastic13, 

Thanks I'm glad you're enjoying the app. 

I've had a couple of issues with this before and from conversations here: https://github.com/SamAmco/track-and-graph/issues/2#issuecomment-634901251 it looks like I basically didn't tag the correct commit in the past. More recently however I can see that the f-droid build server failed. It should retry automatically so I will check back in a few days and hopefully it will have fixed its self. 

Sorry about this.

**Comment by Stochastic13** [comment]
The F-droid version did update but it shows the version to be 1.6.2. I am not sure why is that though.

The displayed changelog however corresponds to versions after 1.7.0. Does it mean the version on F-droid is the 1.7.2 as it show here on Github?

**Comment by SamAmco** [comment]
Hi @Stochastic13 it looks like F-droid tried to build 1.7.2 recently and failed. The last successful build was 1.6.2. The easiest way to know what version of the app you have is to go to the about page and look in the top right corner. Unfortunately we just have to wait for F-droid to try and build 1.7.2 again I think. Sorry I don't have much control over the F-droid build system.

**Comment by SamAmco** [comment]
Hi @Stochastic13 It looks like F-Droid has finally built 1.7.2. Sorry about the delay it just takes a while sometimes I think. It doesn't help that I was naming versions badly for a while which confused it. It should be more consistent going forward.
