### ISSUE TITLE
Support Tracking Free-Form Text as Input Style

### ISSUE THREAD

**Issue by debanjum** [SamAmco/track-and-graph#38]
Firstly, thanks for creating this app, it's super useful! Just had some requests for extending the app to make it even better :)

Currently Track&Graph only supports _date-time_, _numerical_ & _multiple choice_ as input styles. 

Experience Tracking questions like "_What is top of mind?_" or "_Who are you with?_" do not neatly fit into the above three input styles currently supported

**Comment by SamAmco** [comment]
Hi @debanjum thanks for the feedback. Actually there is a notes section in 1.7.x up (if you're on F-droid it should hopefully be released soon but their build system is just a bit slow, it is already up on Google Play). Notes can be added to any data point and will show up in a list underneath any graph they are relevant to :)
