### ISSUE TITLE
is it possible to reset the displayed counter every day?

### ISSUE THREAD

**Issue by emugel** [SamAmco/track-and-graph#40]
Hi, thanks for the wonderful app.
I have been using only since yesterday but find it amazing!

Since I begun to track coffees and cigarets, I was surprised yesterday at midnight to not see the displayed counter reset to zero.

I thought maybe it would have got reset in the night, for instance at 4am, but this.morning it was still not reset. So I figure this is a global counter.

Is it correct?
If yes I am imagining 2 things:
1. An option in edit track: "Counter shows": Total, Daily, Weekly, Monthly. With  a default of Total.
2. Maybe a more global setting called "Time when to reset counter if set so": with a default of "00:00" probably (principle of least surprise).

**Comment by emugel** [comment]
I you do accept PR, and after your feedback, I could try to implement it if you want.

**Comment by SamAmco** [comment]
Hi @emugel, thanks for the feedback, I'm glad you're enjoying the app. 

This feature does not currently exist and you are right that the counter is a global counter. It is really mainly there to show how much data has been tracked. 

May I first suggest that if you want to know the total number of something tracked within a given duration you might be better off creating a graph that shows totals per that duration. For example you could plot a graph that shows the total number of coffees you drank per day in the last week. I use this method to plot exercise like so: 

![Screenshot_20200612_133729_com samco trackandgraph](https://user-images.githubusercontent.com/5012146/84503421-1124c500-acb2-11ea-858f-487159fb1da1.jpg)

Does this meet your needs?

**Comment by emugel** [comment]
The graph is excellent to get a view in time, but to tackle bad habits or meet weekly sales objectives it can not beat a "cigarets: 5 today" or a "sales: 6 this week". Compare that to "cigarets: 5266 tracked" and "sales: 345 tracked" :)

That dashboard is so great as much as possible I want it to be the main screen I used.
To give an example, first day I smoked 15 cigarets: 0 1 2 3 4 5 6 7 .. 13 14. The second day I smoked 14 cigarets: 15 16 17 .. 28 29. I can memorize the number and make a substraction, but when I reach 436 events it will be harder and harder.

**Comment by SamAmco** [comment]
Hmm ok I can see some potential value in this but I don't see it as a great priority right now as I'm working on other areas of the app. If you are interested in taking this on you are welcome, but please create a PR and try to explain in as much detail as you can how this will work and what value it provides before you start implementing anything. It would be good to see some wire frames for the UX on this also. 

One question I would like to see addressed is how the values of multiple choice answers are counted. For example I may track something like Alcohol consumption with the following answers (0:None, 1:Some drinking, 2:Heavy drinking). Suppose I track every day, my week might look as follows:

0:None
1:Some drinking
0...
0...
0...
2:Heavy drinking
0...

What would my counter say for the week? I have tracked 7 items so it could say "7 this week", but the total accounting for heavy drinking would be "3 this week". The plot total graph I posted above would say 3 but the current dashboard card would count all of them as 1 to a total of 7.

More broadly lots of people use the app in different ways to track different things so we need to make sure that the implementation serves as many use cases as possible without making the UX overly complex.

**Comment by emugel** [comment]
See https://github.com/SamAmco/track-and-graph/pull/46
