### ISSUE TITLE
DB Documentation

### ISSUE THREAD

**Issue by azoeart** [SamAmco/track-and-graph#43]
I'd like to manipulate the data externally, but I don't know enough about databases to open the backup file.

What's a good place to start? 

If I could learn enough to export CSV tables I could start. Later I could learn to manipulate the database directly.

I think a few notes about the backup file might be helpful to others who know more and would like to do the same.

Cheers!

PS I love this little app!

**Comment by SamAmco** [comment]
Thanks, I'm glad you're enjoying the app :) 

Personally I use [sqlitebrowser](https://sqlitebrowser.org/) for visually inspecting sqlite databases. You should be able to use this pretty easily to just browse the data in the tables. I'm pretty sure you can export tables to CSV from sqlitebrowser too but I've never tried. 

Also you can also export your tracked data to CSV and re-import it directly from the app. There is a description of this in the FAQ in the app. Please remember to back everything up if you're going to import from a modified CSV or database file though just in case you break something.

**Comment by azoeart** [comment]
Thank you! I'll check sqlitebrowser.

I appreciate the time you've taken to write that up. That last paragraph is way over my head, but will probably help somebody else. :)

Thanks again.
