### ISSUE TITLE
Feature request: Negative time durations

### ISSUE THREAD

**Issue by Kowalevskaja** [SamAmco/track-and-graph#44]
Hello

Congratulations to your great app! I am happily using it to track some time related stuff. Now, I would be in need to enter negative time durations, e.g. "-2h 33m 5s". Your user interface currently exclusively allows to enter numbers to the hh-field. Do you think it could be enhanced to take a leading "minus"-sign? As far as I know time durations are signed data types and therewith natively allow for negative values.

Many thanks in advance and keep up the great work!

**Comment by SamAmco** [comment]
Interesting. Yes I think this should be doable. I will try and take a look when I get time.

**Comment by SamAmco** [comment]
Can't remember when but I'm pretty sure I fixed this. Let me know if you have any other issues and i can open the ticket again but it should all be working fine.

**Comment by Kowalevskaja** [comment]
Yes, this is fixed and works like a charm. Many thanks!
