### ISSUE TITLE
Application crash when using the | symbol 

### ISSUE THREAD

**Issue by Lambd-Alex** [SamAmco/track-and-graph#48]
Using the | symbol in the name of a choice in multiple choices tracker cause the app to crash when saving the tracker.
The group tracker who contains such tracker can no longer be used without crashing the app.

Android 8.1.0, LineageOS 15.1

**Comment by SamAmco** [comment]
Thank you for drawing my attention to this. I will try and look into it soon.

**Comment by SamAmco** [comment]
Hi @Lambd-Alex I'm sorry about this bug. This is a case of bad practice on my part. I will be releasing a fix in the near future for this. The fix will automatically delete any trackers that use pipe characters when you update the app to 10.0.2. However after the update you should be safe to use what ever characters you like. I hope this is ok for you?

**Comment by Lambd-Alex** [comment]
Ok, thanks you very much for the fix :)
Well it's OK, I can't use them anymore anyway ^^
