### ISSUE TITLE
Feature request: Add more time options for "Average time between"

### ISSUE THREAD

**Issue by Kozonak** [SamAmco/track-and-graph#50]
For _average time between_ the only measurement available is days. Unless I missed something, but I did fiddle with the numbers and it doesnt look like I can change it to something else.

Can we have a dropdown or something to switch from year/month/week/day/hour/minutes? It works now for things tracked weekly but for multiple per days it will only show 0.1/0.2 days.

**Comment by SamAmco** [comment]
I think this would probably be best solved with better formatting. I will update the formatting code to display hours/minutes etc when appropriate.

**Comment by SamAmco** [comment]
I think i fixed this a while back and forgot to close this ticket.
