### ISSUE TITLE
Given a time range, show total - numeric type tracking

### ISSUE THREAD

**Issue by tumstech** [SamAmco/track-and-graph#51]
I have a range of numeric type being tracked. There is an option to check the usage based on daily / weekly for total / average
Need a way to find what is the total being tracked... Not tracking count, looking for tracking cumulatively

Another alternative, to show total without timerange in the tracking bubble. 
Dont know much, but i think a new string just like this would help my needs as of now. https://github.com/SamAmco/track-and-graph/blob/885a5e02c58f8fb3fed20846e31abc804f98336a/app/src/main/java/com/samco/trackandgraph/displaytrackgroup/FeatureAdapter.kt#L88

**Comment by SamAmco** [comment]
I am going to close this issue as I believe it has been discussed in the linked PR's. Whether it will be fully implemented in the near future is hard to say right now. I may also simply create a cumulative total graph/stat to solve this, again I have no time frame on that atm. Thanks for your patience.
