### ISSUE TITLE
menu partly overwritten

### ISSUE THREAD

**Issue by paulle** [SamAmco/track-and-graph#57]
Menu partly overwritten. 
sony experia 5, android10, display resolution 1080 x 2520   21:9
![Screenshot_20201129-003931](https://user-images.githubusercontent.com/4852079/100545329-a402ed00-325b-11eb-9861-3068bf2314ab.png)

**Comment by SamAmco** [comment]
Thank you for reporting this I will try and take a look soon

**Comment by SamAmco** [comment]
Sorry it took me so long, this should be fixed in the next release
