### ISSUE TITLE
ability to "merge" TRACKERS on a chart

### ISSUE THREAD

**Issue by pierrrek** [SamAmco/track-and-graph#61]
Sorry for flooding you with ideas and this one is probably the most complicated. Or maybe the easiest, depending on database layout. 

[As an example] I may be tracking carb volume and alcohol volume separately, but want to see them combined on a chart against something else. Currently they may both look insignificant when charted, but leads to a better story when daily values can be combined. I currently deal with that by exporting my data, copying both sets (or three or more), renaming the first column, reload and voila. 

Alteration: I believe that this can be very easily done by either allowing for multiple selections (tickbox) when choosing the Tracker in the drop-down list or allowing for an additional Tracker in any given chart. It won't work well on "plot when tracked" or maybe it will.

**Comment by lenalebt** [comment]
I built the feature this morning. I would not necessarily say it's the cleanest implementation, but it works and is not very invasive in the code. Some example screenshots:
![grafik](https://user-images.githubusercontent.com/697104/121772782-ec3e8880-cb77-11eb-98ca-dc76067668b3.png)

No data modification:
![grafik](https://user-images.githubusercontent.com/697104/121772794-fceefe80-cb77-11eb-9fe0-c7c897ce471f.png)
Stack graphs:
![grafik](https://user-images.githubusercontent.com/697104/121772797-0710fd00-cb78-11eb-9221-ab6293ed3ff5.png)
Sum graphs:
![grafik](https://user-images.githubusercontent.com/697104/121772801-109a6500-cb78-11eb-82ce-ba429f6f8740.png)

I basically just added a post-data-fetch step in `LineGraphDataFactory.kt`. Imho it could be changed later on to support the linked "Add data transformation" feature, but I did not need it full-fledged. This way, you can track e.g. individual sports but still see a graph with the sum of them all.

I could make this PR-ready if you are interested :).

**Comment by lenalebt** [comment]
I just added the PR, I mean, I'm happy to make changes to the impl anyways and need to test it myself, but this way we can discuss it and have a look.

**Comment by dummifiedme** [comment]
Was this feature included in the main app?

**Comment by SamAmco** [comment]
This was not included in the main app. The sum of two data sets is just one of many transformations that one might want to do and I don't want to start down the road of adding UI for all of them because it's too confusing for most users and users new to the app. To this end though I am intending on introducing a basic language to the app that will hopefully provide all the power you need. This is a big feature though and could take quite a while. See #69
