### ISSUE TITLE
Keyboard doesn't go away after tracking via widget

### ISSUE THREAD

**Issue by randomshinichi** [SamAmco/track-and-graph#63]
I add something via a widget
![Screenshot_2020-12-31-09-12-29-950_com.samco.trackandgraph.jpg](https://user-images.githubusercontent.com/9956122/103401346-bddc6c00-4b48-11eb-9f3b-9a3ec9d4ff7d.jpg)

The numerical keyboard changes but the keyboard still stays. I'm using Gboard.
![Screenshot_2020-12-31-09-13-33-189_com.miui.home.jpg](https://user-images.githubusercontent.com/9956122/103401378-d5b3f000-4b48-11eb-8bea-f8dedcf039b4.jpg)

Seems like a simple issue,could you guide me to where/how to make the fix?

**Comment by SamAmco** [comment]
Thanks for pointing this out. I'm not sure where the bug lies right now.  I will try and take a look into it at some point.

**Comment by SamAmco** [comment]
I wasn't really able to re-produce this issue. The android code around keyboard showing/hiding is horrible so i think it produces some odd behaviour on some devices sometimes. I tried to add a fallback force hide keyboard when the tracking completes so hopefully that will work in the next release. Feel free to re-open if it doesn't.
