### ISSUE TITLE
Feature: Use reasonable y-intervals (in line plots)

### ISSUE THREAD

**Issue by hhpmmd** [SamAmco/track-and-graph#68]
Right now the y-intervals displayed on the left of the graphs (for line plots) is always min+n*(max-min)/10 for n from 0 to 10.

This works nicely for min = 0, max = 1, 10 etc. but not for other intervals like (0,7) (see image)
![bad_y_steps](https://user-images.githubusercontent.com/77058867/105981427-5a395600-6096-11eb-87e2-eecfbee7c544.png)

It would be nicer to just have y-intervals of 1 (instead of 0.7) here.

Possible solution:
Right now the interval is set using `binding!!.xyPlot.setRangeStep(StepMode.SUBDIVIDE, 11.0)`. The `setRangeStep` method also supports using a fixed interval (`StepMode.INCREMENT_BY_VALUE`) which would have to be calculated beforehand. The algorithm for this fixed interval should come up with a reasonable interval (0.1,0.2,0.5,1,2,5,10,15,20,25,50,75,100 etc) that roughly divides the min-max-space by 11 steps. 
(I didn't come up with any smart ways to do this but a more brute force approach should also do).

There are two downsides to the fixed interval method:
- the min value has to be a multiple of the interval for this to make sense (-> the min value of the plot no longer shows the min value of the data if it's not a multiple)
- if the max value is not a multiple of the (new) interval, it won't be shown as a y-label.

Therefore there would probably be some padding above and below the graphs.

I can probably implement this myself, though I wanted to get some feedback here first.

**Comment by SamAmco** [comment]
Yes this is an issue I am aware of and I haven't been able to think of an elegant solution yet. If you have a good idea I'd be very happy to see it implemented. There's nothing special about 11, just that it gives you 0-10 nicely. If you can find a reliable and easy way to find a nicer factor of the range then you can change the number of y steps depending on the data. So for your graph above it probably makes the most sense just to have 0-7 in increments of 1. 

It's probably best if you calculate this data in the LineGraphDataFactory and pass it in to the decorator through the ILineGraphViewData object. 

Thanks for looking into this!
