### ISSUE TITLE
Need Visual clue for widget action

### ISSUE THREAD

**Issue by aproposnix** [SamAmco/track-and-graph#77]
First off, this is a really simple but awesome app. Thanks a lot for creating and maintaining it. 

**the issue**

When a user clicks on a widget icon on the desktop, it is very difficult to tell if it has been clicked or not. This can result in the user accidentally  clicking it more than once. 

**proposal** 

Provide better visual clues on click/tap action such as: 
* Briefly changing the color of the button
* change the text to "confirmed!" 
* haptic feedback

**Comment by SamAmco** [comment]
Thanks for bringing this to my attention. I will add it to my backlog.

**Comment by SamAmco** [comment]
Ok I've added haptic feedback for the next release. There is also a visual effect that's already in there but perhaps it doesn't work on all devices.
