### ISSUE TITLE
Invisible "no" on deletion of group confirmation dialog

### ISSUE THREAD

**Issue by Kyle2142** [SamAmco/track-and-graph#82]
![Screenshot_20210326-113301265](https://user-images.githubusercontent.com/19349418/112612217-553f1b80-8e27-11eb-9b0a-5c707425ab77.jpg)
The button is there but seems to have no text

**Comment by SamAmco** [comment]
Well spotted, thank you i will try to fix this soon.

**Comment by SamAmco** [comment]
Will be fixed in the next release
