### ISSUE TITLE
Application crash when trying to edit or add anything

### ISSUE THREAD

**Issue by Kozonak** [SamAmco/track-and-graph#84]
1.12.0 from f-droid
Android 9 (k 4.9.148)

App crashes when trying to edit or add a graph.

Time since last, average time, etc, they all crash when I push the edit button. 

Duplicating, moving, deleting still work.

Edit: Editing the things you track works ok.

**Comment by SamAmco** [comment]
Hi, that's a concerning bug. I'm unable to see this issue on my device. Are you able to produce a log of the crash or an exact set of steps to reproduce the issue after a fresh install of the app. Alternatively if you don't mind sharing your data you could back it up using the backup/restore feature and send me the .db file for me to import and test. If the data is personal/sensitive you could back it up, change all the names and then backup again and send me the second backup. You can email it to help.trackandgraph@gmail.com. It is likely that there is some specific configuration in your tracked data that is causing the crash. Anything you can do to help me track this down would be very helpful. Thank you

**Comment by Kozonak** [comment]
From the crash log

```
FATAL EXCEPTION: main
Process: com.samco.trackandgraph, PID: 24542
android.view.InflateException: Binary XML file line #110: Binary XML file line #110: Error inflating class TextView
Caused by: android.view.InflateException: Binary XML file line #110: Error inflating class TextView
Caused by: android.content.res.Resources$NotFoundException: Drawable com.samco.trackandgraph:color/bg_hold_to_preview with resource ID #0x7f060026
Caused by: android.content.res.Resources$NotFoundException: File res/color/bg_hold_to_preview.xml from drawable resource ID #0x7f060026
```

I'm going to try a fresh install on another device with my db and see if its the same.

**Comment by SamAmco** [comment]
Ok I managed to find and fix this bug thanks to the crash log you emailed me. Thanks again for reporting this before it got out of beta, you're a track and graph hero.

**Comment by SamAmco** [comment]
@allcontributors bot please add @Kozonak for bug
