### ISSUE TITLE
Missing space between date and time

### ISSUE THREAD

**Issue by Kozonak** [SamAmco/track-and-graph#87]
v 1.13.0

There is a missing space between the date and the time.

![image](https://user-images.githubusercontent.com/3283978/114526024-480b9480-9c4f-11eb-8490-e7222665d914.png)

**Comment by SamAmco** [comment]
Thanks for picking up on this, I noticed this the other day also, will aim to fix soon.

**Comment by SamAmco** [comment]
fixed.
