### ISSUE TITLE
App crashes when using Daily Totals with zero data points

### ISSUE THREAD

**Issue by pizzapim** [SamAmco/track-and-graph#9]
Steps to reproduce:

1. Create a new tracker with date and time only.
2. Create a new line graph, add the newly created tracker and enable Plot Daily Totals.
3. App crashes.

**Comment by SamAmco** [comment]
Thanks for the heads up I have noticed a few crash reports around this, I will take a look ASAP.

**Comment by pizzapim** [comment]
@SamAmco Thanks for the quick response, can confirm 681d087f53b63b40fff8536a33c518b6d138fc07 fixes the bug.
