### ISSUE TITLE
Ask for Confirmation Before Deleting a Graph

### ISSUE THREAD

**Issue by alphanerdgen** [SamAmco/track-and-graph#91]
Today I deleted a graph accidentally. 😓 If only the app had asked me for confirmation before deleting it forever. It does ask before deleting Track Groups so why not also for Graphs?

**Comment by SamAmco** [comment]
Sorry to hear this. Perhaps you are right that there should be a delete confirmation on graphs. My impression was that they are generally pretty quick and easy to set up and so the convenience of being able to remove them quickly outweighs the convenience of not deleting them by mistake. This maybe is no longer the case as graphs can get quite complex.

**Comment by SamAmco** [comment]
This is done now. Thanks for the wait.
