### ISSUE TITLE
Add french langage

### ISSUE THREAD

**Issue by tifriis208** [SamAmco/track-and-graph#93]
Hi, thanks for this great app.
I would like to help to translate your app in french :) I reviewed the code, do I need to commit a translated file "value-fr" ? I found spanish and dutch langage in the code but I didn't find how to switch langage in the application. thanks !

**Comment by e-t-l** [comment]
Yes, you'd want to submit a pull request with a new folder and file: **track-and-graph/app/src/main/res/values-fr/strings.xml**. The app defaults to the device's system-wide language (tested it just now by changing my system language to Spanish. Track and Graph immediately changed all strings to Spanish). There isn't currently an in-app way to override this (although you could always compile your own version of the app where you've replaced the default strings.xml file with one in your preferred language).

**Comment by SamAmco** [comment]
Thanks @e-t-l this is correct. Make sure you only modify the text that's inside of the xml body's though. Don't translate the name attributes as they are used in code ;)

**Comment by tifriis208** [comment]
perfect, I will try to translate it in french this week
