### ISSUE TITLE
Feature Request: Pinned graphs

### ISSUE THREAD

**Issue by e-t-l** [SamAmco/track-and-graph#95]
(First off, hi! Love this app, it's really helped me better manage many aspects of my life!)
Would it be possible to add the ability to pin graphs to the home page? It would be a nice quick way to see some frequently-viewed graphs right when opening the app, rather than having to tap through to the specific graph group and scroll to the appropriate graph.

**Comment by SamAmco** [comment]
Actually you are not the first person to ask for this and this falls in the same basket as allowing trackers to be added to the home page, which people have also asked for. I think the best idea here is to remove the distinction between graph groups and track groups entirely and just have groups. The home page is the root group and any group can contain trackers, graphs/stats and more groups. Then you just end up with a flexible tree structure like a directory hierarchy. I would like to implement this properly at some point but it's probably a slightly more time consuming change so it could take a while.

**Comment by SamAmco** [comment]
Hi, thanks for your patience, this feature should now be available as described in my previous comment with the release of 2.0 (which is currently in beta on the playstore)
